  
name: "CI"

on: [push]

jobs:
  job_1:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1.0.0
      with: 
        cordova-version: 9.0.0
        ionic-version: 5.4.13
        install-java: true
    - name: Run cordova project tests
      run: |
        ionic info
        ionic cordova platform add android@latest
        ionic cordova build android
